# -*- coding: utf-8 -*-
"""DDPG_Final_2_state.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbuDvj5rTg68_5WrEOwWBg3zogK1PkoM
"""

"""
Title: Deep Deterministic Policy Gradient (DDPG)
Author: [amifunny](https://github.com/amifunny)
Date created: 2020/06/04
Last modified: 2020/09/21
Description: Implementing DDPG algorithm on the Inverted Pendulum Problem.
"""
"""
## Introduction

**Deep Deterministic Policy Gradient (DDPG)** is a model-free off-policy algorithm for
learning continous actions.

It combines ideas from DPG (Deterministic Policy Gradient) and DQN (Deep Q-Network).
It uses Experience Replay and slow-learning target networks from DQN, and it is based on
DPG,
which can operate over continuous action spaces.

This tutorial closely follow this paper -
[Continuous control with deep reinforcement learning](https://arxiv.org/pdf/1509.02971.pdf)

## Problem

We are trying to solve the classic **Inverted Pendulum** control problem.
In this setting, we can take only two actions: swing left or swing right.

What make this problem challenging for Q-Learning Algorithms is that actions
are **continuous** instead of being **discrete**. That is, instead of using two
discrete actions like `-1` or `+1`, we have to select from infinite actions
ranging from `-2` to `+2`.

## Quick theory

Just like the Actor-Critic method, we have two networks:

1. Actor - It proposes an action given a state.
2. Critic - It predicts if the action is good (positive value) or bad (negative value)
given a state and an action.

DDPG uses two more techniques not present in the original DQN:

**First, it uses two Target networks.**

**Why?** Because it add stability to training. In short, we are learning from estimated
targets and Target networks are updated slowly, hence keeping our estimated targets
stable.

Conceptually, this is like saying, "I have an idea of how to play this well,
I'm going to try it out for a bit until I find something better",
as opposed to saying "I'm going to re-learn how to play this entire game after every
move".
See this [StackOverflow answer](https://stackoverflow.com/a/54238556/13475679).

**Second, it uses Experience Replay.**

We store list of tuples `(state, action, reward, next_state)`, and instead of
learning only from recent experience, we learn from sampling all of our experience
accumulated so far.

Now, let's see how is it implemented.
"""
import gym
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as ode

"""
We use [OpenAIGym](http://gym.openai.com/docs) to create the environment.
We will use the `upper_bound` parameter to scale our actions later.
"""

problem = "Pendulum-v0"
env = gym.make(problem)

#num_states = env.observation_space.shape[0]
num_states = 2
print("Size of State Space ->  {}".format(num_states))
#num_actions = env.action_space.shape[0]
num_actions = 1
print("Size of Action Space ->  {}".format(num_actions))

#upper_bound = env.action_space.high[0]
upper_bound = 20
#lower_bound = env.action_space.low[0]
lower_bound = -20

print("Max Value of Action ->  {}".format(upper_bound))
print("Min Value of Action ->  {}".format(lower_bound))

"""
To implement better exploration by the Actor network, we use noisy perturbations,
specifically
an **Ornstein-Uhlenbeck process** for generating noise, as described in the paper.
It samples noise from a correlated normal distribution.
"""

class OUActionNoise:
    def __init__(self, mean, std_deviation, theta=0.1, dt=0.1, x_initial=None):
        self.theta = theta
        self.mean = mean
        self.std_dev = std_deviation
        self.dt = dt
        self.x_initial = x_initial
        self.reset()

    def __call__(self):
        # Formula taken from https://www.wikipedia.org/wiki/Ornstein-Uhlenbeck_process.
        x = (
            self.x_prev
            + self.theta * (self.mean - self.x_prev) * self.dt
            + self.std_dev * np.sqrt(self.dt) * np.random.normal(size=self.mean.shape)
        )
        # Store x into x_prev
        # Makes next noise dependent on current one
        self.x_prev = x
        return x

    def reset(self):
        if self.x_initial is not None:
            self.x_prev = self.x_initial
        else:
            self.x_prev = np.zeros_like(self.mean)

"""
The `Buffer` class implements Experience Replay.

---
![Algorithm](https://i.imgur.com/mS6iGyJ.jpg)
---


**Critic loss** - Mean Squared Error of `y - Q(s, a)`
where `y` is the expected return as seen by the Target network,
and `Q(s, a)` is action value predicted by the Critic network. `y` is a moving target
that the critic model tries to achieve; we make this target
stable by updating the Target model slowly.

**Actor loss** - This is computed using the mean of the value given by the Critic network
for the actions taken by the Actor network. We seek to maximize this quantity.

Hence we update the Actor network so that it produces actions that get
the maximum predicted value as seen by the Critic, for a given state.
"""


class Buffer:
    def __init__(self, buffer_capacity=100000, batch_size=64):
        # Number of "experiences" to store at max
        self.buffer_capacity = buffer_capacity
        # Num of tuples to train on.
        self.batch_size = batch_size

        # Its tells us num of times record() was called.
        self.buffer_counter = 0

        # Instead of list of tuples as the exp.replay concept go
        # We use different np.arrays for each tuple element
        self.state_buffer = np.zeros((self.buffer_capacity, num_states))
        self.action_buffer = np.zeros((self.buffer_capacity, num_actions))
        self.reward_buffer = np.zeros((self.buffer_capacity, 1))
        self.next_state_buffer = np.zeros((self.buffer_capacity, num_states))
        self.d_buffer = np.zeros((self.buffer_capacity, 1))

    # Takes (s,a,r,s',d) obervation tuple as input
    def record(self, obs_tuple):
        # Set index to zero if buffer_capacity is exceeded,
        # replacing old records
        index = self.buffer_counter % self.buffer_capacity

        self.state_buffer[index] = obs_tuple[0]
        self.action_buffer[index] = obs_tuple[1]
        self.reward_buffer[index] = obs_tuple[2]
        self.next_state_buffer[index] = obs_tuple[3]
        self.d_buffer[index] = obs_tuple[4]
        self.buffer_counter += 1

    # Eager execution is turned on by default in TensorFlow 2. Decorating with tf.function allows
    # TensorFlow to build a static graph out of the logic and computations in our function.
    # This provides a large speed up for blocks of code that contain many small TensorFlow operations such as this one.
    @tf.function
    def update(
        self, state_batch, action_batch, reward_batch, next_state_batch, d_batch
    ):
        # Training and updating Actor & Critic networks.
        # See Pseudo Code.
        with tf.GradientTape() as tape:
            target_actions = target_actor(next_state_batch, training=True)
            y = reward_batch + gamma * tf.math.multiply(d_batch,    target_critic(
                [next_state_batch, target_actions], training=True)   )
            critic_value = critic_model([state_batch, action_batch], training=True)
            critic_loss = tf.math.reduce_mean(tf.math.square(y - critic_value))
        critic_grad = tape.gradient(critic_loss, critic_model.trainable_variables)
        critic_optimizer.apply_gradients(
            zip(critic_grad, critic_model.trainable_variables)
        )

        with tf.GradientTape() as tape:
            actions = actor_model(state_batch, training=True)
            critic_value = critic_model([state_batch, actions], training=True)
            # Used `-value` as we want to maximize the value given
            # by the critic for our actions
            actor_loss = -tf.math.reduce_mean(critic_value)

        actor_grad = tape.gradient(actor_loss, actor_model.trainable_variables)
        actor_optimizer.apply_gradients(
            zip(actor_grad, actor_model.trainable_variables)
        )

    # We compute the loss and update parameters
    def learn(self):
        # Get sampling range
        record_range = min(self.buffer_counter, self.buffer_capacity)
        # Randomly sample indices
        batch_indices = np.random.choice(record_range, self.batch_size)

        # Convert to tensors
        state_batch = tf.convert_to_tensor(self.state_buffer[batch_indices])
        action_batch = tf.convert_to_tensor(self.action_buffer[batch_indices])
        reward_batch = tf.convert_to_tensor(self.reward_buffer[batch_indices])
        reward_batch = tf.cast(reward_batch, dtype=tf.float32)
        next_state_batch = tf.convert_to_tensor(self.next_state_buffer[batch_indices])
        d_batch = tf.convert_to_tensor(self.d_buffer[batch_indices])
        d_batch = tf.cast(d_batch, dtype=tf.float32)
        self.update(state_batch, action_batch, reward_batch, next_state_batch,d_batch)

        target_actions = target_actor(next_state_batch, training=True)
        y = reward_batch + gamma * tf.math.multiply(d_batch,    target_critic(   [next_state_batch, target_actions], training=True)   )
        critic_value = critic_model([state_batch, action_batch], training=True)
        self.critic_loss = tf.math.reduce_mean(tf.math.square(y - critic_value))

        actions = actor_model(state_batch, training=True)
        critic_value = critic_model([state_batch, actions], training=True)
        # Used `-value` as we want to maximize the value given
        # by the critic for our actions
        self.actor_loss = -tf.math.reduce_mean(critic_value)

# This update target parameters slowly
# Based on rate `tau`, which is much less than one.
@tf.function
def update_target(target_weights, weights, tau):
    for (a, b) in zip(target_weights, weights):
        a.assign(b * tau + a * (1 - tau))



"""# Network Structure"""

"""
Here we define the Actor and Critic networks. These are basic Dense models
with `ReLU` activation.

Note: We need the initialization for last layer of the Actor to be between
`-0.003` and `0.003` as this prevents us from getting `1` or `-1` output values in
the initial stages, which would squash our gradients to zero,
as we use the `tanh` activation.
"""
from keras.layers import Lambda
from keras import backend as K
from tensorflow.keras.layers import Reshape
global t
t = 0.0
def sign_func(a):
    w = 1.0
    m = 1
    s1 = tf.gather(a, 0, axis=1)
    s2 = tf.gather(a, 1, axis=1)
    #b = 8.6*x1 - 5.8*x2 - tf.math.pow(x2,2)
    #b = x1 + tf.math.pow(x1,2) - x2
    b = s1 + s2
    return m*K.sign(tf.reduce_sum(a,axis=1))
    #return - m*K.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))
def sum_out(input):
    return tf.reduce_sum(input,axis=1)

def get_actor():
    # Initialize weights between -3e-3 and 3-e3
    last_init = tf.random_uniform_initializer(minval=-0.01, maxval=0.01)

    inputs = layers.Input(shape=(num_states,))
    out = layers.Dense(512, activation="relu")(inputs)
    out = layers.Dense(512, activation="relu")(out)
    out = layers.Dense(512, activation="relu")(out)
    out = layers.Dense(512, activation="relu")(out)
    out = layers.Dense(64, activation="relu")(out)
    output1 = layers.Dense(1, activation="linear", kernel_initializer=last_init)(out)
    output2 = layers.Dense(1, activation="tanh", kernel_initializer=last_init)(out)
    output3 = Lambda(sign_func)(inputs)
    output3 = Reshape((1,))(output3)
    output3 = tf.keras.layers.Multiply()([output2,output3])
    output = layers.Concatenate()([output1, output3])
    output = Lambda(sum_out)(output)
    output = Reshape((1,))(output)
    model = tf.keras.Model(inputs, output)
    #model = tf.keras.Model(inputs, output1)
    return model


def get_critic():
    # State as input
    state_input = layers.Input(shape=(num_states))
    state_out = layers.Dense(512, activation="relu")(state_input)
    state_out = layers.Dense(512, activation="relu")(state_out)
    state_out = layers.Dense(512, activation="relu")(state_out)

    # Action as input
    action_input = layers.Input(shape=(num_actions))
    action_out = layers.Dense(512, activation="relu")(action_input)
    action_out = layers.Dense(512, activation="relu")(action_out)
    action_out = layers.Dense(512, activation="relu")(action_out)

    # Both are passed through seperate layer before concatenating
    concat = layers.Concatenate()([state_out, action_out])

    out = layers.Dense(512, activation="relu")(concat)
    out = layers.Dense(512, activation="relu")(out)
    outputs = layers.Dense(1)(out)

    # Outputs single value for give state-action
    model = tf.keras.Model([state_input, action_input], outputs)

    return model

"""
`policy()` returns an action sampled from our Actor network plus some noise for
exploration.
"""


def policy(state, noise_object):
    sampled_actions = tf.squeeze(actor_model(state))
    noise = noise_object()
    # Adding noise to action
    sampled_actions = sampled_actions.numpy() + noise
    # We make sure action is within bounds
    legal_action = np.clip(sampled_actions, lower_bound, upper_bound)

    return [np.squeeze(legal_action)]

def policy1(state, noise_object):
    sampled_actions = tf.squeeze(actor_model(state))
    # Adding noise to action
    sampled_actions = sampled_actions.numpy()
    # We make sure action is within bounds
    legal_action = np.clip(sampled_actions, lower_bound, upper_bound)
    return [np.squeeze(legal_action)]

"""
## Training hyperparameters
"""

std_dev = 0.1   # used to be 0.1
ou_noise = OUActionNoise(mean=np.zeros(1), std_deviation=float(std_dev) * np.ones(1))

actor_model = get_actor()
critic_model = get_critic()

target_actor = get_actor()
target_critic = get_critic()

# Making the weights equal initially
target_actor.set_weights(actor_model.get_weights())
target_critic.set_weights(critic_model.get_weights())

# Learning rate for actor-critic models
critic_lr = 0.005   # used to be 0.005
actor_lr = 1 * 10**(-4)   #5     -4

critic_optimizer = tf.keras.optimizers.Adam(critic_lr)
actor_optimizer = tf.keras.optimizers.Adam(actor_lr)

total_episodes = 1000
# Discount factor for future rewards
gamma = 1.0
# Used to update target networks
tau = 0.005

buffer = Buffer(60000, 70)

"""# Simplified SYstem VS Original System without DDPG"""

def sys1(t, y):
    s1, s2 = y
    u = ( 1/(19.24+9.6*s2)  )*(2.8*s1-8.6*s2-5.8*np.power(s2,2)-2*np.power(s2,3)-2*s1*s2)\
        + ( 2/(19.24+9.6*s2)  )*np.sign(8.6*s1-5.8*s2-np.power(s2,2))
    dydt = [s1-s2 + u , s1+np.power(s2,2)+4.8*u]
    return dydt
s0 = np.array([0.5,0])


def sys1(t, y):
    s1, s2 = y
    u = (1/4.8) * (np.power(s1,2)-s2+2*np.power(s1,3)-2*s1*s2-s1-np.power(s2,2))  +  (1/4.8) * np.sign(s1+np.power(s1,2)-s2)
    dydt = [np.power(s1,2)-s2, s1+np.power(s2,2)+4.8*u]
    return dydt


def sys1(t, y):
    s1, s2 = y
    c = 2
    k = 5
    b = 1.5
    m = 1
    w = 1
    u = m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) - np.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))*m
    dydt = [s2, 1/m*(-c*s2-k*s1 + u)]
    return dydt





def sys2(t, y):
    s1, s2 = y
    c = 2
    k = 5
    b = 1.5
    m = 1
    w = 1
    u = m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) - np.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))*m
    dydt = [s2, 1/m*(-c*s2*np.abs(s2)-k*s1 - b*np.power(s1,3) + u)]
    return dydt



###############################################################################################################
initial_states = np.array([0,0])
s0 = initial_states

s_ref = []
u_ref = []
y_ref = []
c = 2
k = 5
b = 1.5
m = 1
w = 1
for i in range(150):
    t = i*0.1
    s_ref.append(s0)
    s1 = s_ref[-1][0]
    s2 = s_ref[-1][1]
    y_ref.append(-1+np.sin(w*t))
    u_ref.append (  m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) - np.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))*m   )
    s0 = ode.solve_ivp(sys1, [t, t+0.1], s0, \
                               method = "RK45",t_eval=[t+0.1])
    s0 = s0.y[:,-1]


s0 = initial_states
s_ref2=[]
for i in range(150):
    t = i*0.1
    s_ref2.append(s0)
    s0 = ode.solve_ivp(sys2, [t, t+0.1], s0, \
                               method = "RK45",t_eval=[t+0.1])
    s0 = s0.y[:,-1]

plt.plot(range(len(y_ref)),y_ref,color='r',marker='o')
plt.plot(range(len(s_ref)),s_ref)
plt.plot(range(len(s_ref2)),s_ref2,'k')
plt.plot(range(len(u_ref)),u_ref)

"""# main"""

"""
Now we implement our main training loop, and iterate over episodes.
We sample actions using `policy()` and train with `learn()` at each time step,
along with updating the Target networks at a rate `tau`.
"""

# To store reward history of each episode
ep_reward_list = []
# To store average reward history of last few episodes
avg_reward_list = []


def sys(t, y):
    s1, s2 = y
    u = ( 1/(19.24+9.6*s2)  )* (2.8*s1-8.6*s2-5.8*np.power(s2,2)-2*np.power(s2,3)-2*s1*s2)- action[0]
    dydt = [s1-s2 + u , np.sin(s1)+np.power(s2,2)+(4)*(1.2-np.exp(-np.absolute(s1)))*u]
    return dydt


def sys(t, y):
    s1, s2 = y
    u = (1/4.8) * (np.power(s1,2)-s2+2*np.power(s1,3)-2*s1*s2-s1-np.power(s2,2)) + action[0]
    dydt = [np.power(s1,2)-s2, np.sin(s1)+np.power(s2,2)+(4)*(1.2-np.exp(-np.absolute(s1)))*u]
    return dydt


def sys(t, y):
    s1, s2 = y
    c = 2
    k = 5
    b = 1.5
    m = 1
    w = 1
    u = (  m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) - np.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))*m   ) + action[0]
    #u = action[0]
    #u = (  m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2)   ) + action[0]
    dydt = [s2, 1/m*(-c*s2*np.abs(s2)-k*s1 - b*np.power(s1,3) + u)]
    return dydt

c = 2
k = 5
b = 1.5
m = 1
w = 1


ep = 0

while ep < total_episodes:
    prev_state = initial_states
    episodic_reward = 0
    numstep = 0
    avg_act = []
    break_flag = 0

    while True:
        t = numstep*0.1
        # Uncomment this to see the Actor in action
        # But not in a python notebook.
        # env.render()
        if np.isnan(prev_state).any()==True:
            print('prev_state is nan')
            break
            break_flag = 1
            ep = total_episodes
        elif np.isinf(prev_state).any()==True:
            print('prev_state is inf')
            break
            break_flag = 1
            ep = total_episodes
        tf_prev_state = tf.expand_dims(tf.convert_to_tensor(prev_state-s_ref[numstep]), 0)
        action = policy(tf_prev_state, ou_noise)
        #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   print a specific layer output
        # outputs=[]
        # layer = actor_model.layers[-5]
        # keras_function = K.function([actor_model.input], [layer.output])
        # outputs=keras_function(tf_prev_state)
        # print(outputs)
        #%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        avg_act.append(action)
        if np.isnan(action).any()==True:
            print('action is nan')
            break
            break_flag = 1
            ep = total_episodes
        elif np.isinf(action).any()==True:
            print('action is inf')
            break
            break_flag = 1
            ep = total_episodes
        y0 = ode.solve_ivp(sys, [t, t+0.1], prev_state, \
                               method = "RK45",t_eval=[t+0.1])
        state = y0.y[:,-1]
        if np.isnan(state).any()==True:
            print('state is nan')
            break
            break_flag = 1
            ep = total_episodes
        elif np.isinf(state).any()==True:
            print('state is inf')
            break
            break_flag = 1
            ep = total_episodes
        reward = -(   (state[0]-s_ref[numstep][0])**2 + (state[1]-s_ref[numstep][1] )**2     )
        #reward = -(   (state[0]-s_ref[numstep][0])**2 + (state[1]-s_ref[numstep][1])**2  + ( 0.001*(  m* (-state[1] + w*np.cos(w*t)\
                #-w*w*np.sin(w*t)+k/m*state[0]+c/m*state[1])  + action[0] ) )**2     )
        episodic_reward += reward
        if np.isnan(reward).any()==True:
            print('reward is nan')
            break
            ep = total_episodes
        elif np.isinf(reward).any()==True:
            print('reward is inf')
            break
            break_flag = 1
            ep = total_episodes
        if episodic_reward <= -20 or numstep>=70:
            #d_stat = np.array([0])
            d_stat = np.array([1])
        else:
            d_stat = np.array([1])
        buffer.record((  prev_state-s_ref[numstep]    , action, reward,  state-s_ref[numstep+1], d_stat ))
        buffer.learn()
        if break_flag ==0:
          update_target(target_actor.variables, actor_model.variables, tau)
          update_target(target_critic.variables, critic_model.variables, tau)
        # End this episode when `done` is True
        if episodic_reward <= -20 or numstep>=70:   #used to be -5
            break

        prev_state = state
        numstep+=1


    ep_reward_list.append(episodic_reward/numstep)
    ep+=1
    # Mean of last 40 episodes
    avg_reward = np.mean(ep_reward_list[-1:])
    avg_act = np.array(avg_act)
    print('------------------------------------------------------------------------------------------------------')
    print("Episode * {} *".format(ep))
    print(" Avg Reward per numstep is ==> {}".format(avg_reward/numstep) , "   and Avg Reward is ==> {}".format(avg_reward))
    print ('critic_loss >>>' , buffer.critic_loss.numpy() , '    actor_loss >>>' , buffer.actor_loss.numpy()\
          , '|    avg action',np.mean(avg_act,0))
    if np.isnan(buffer.critic_loss.numpy()).any()==True or np.isnan(buffer.actor_loss.numpy()).any()==True:
        ep = total_episodes
    avg_reward_list.append(avg_reward)
    if np.abs((avg_reward)) <0.08 and ep>=100:
      std_dev =0.01
    else:
      std_dev =0.1
    if np.abs((avg_reward)) <0.026 and numstep>=70 and ep>=100:
      ep = 100000
# Plotting graph
# Episodes versus Avg. Rewards
plt.plot(avg_reward_list)
plt.xlabel("Episode")
plt.ylabel("Avg. Epsiodic Reward")
plt.show()

"""
If training proceeds correctly, the average episodic reward will increase with time.

Feel free to try different learning rates, `tau` values, and architectures for the
Actor and Critic networks.

The Inverted Pendulum problem has low complexity, but DDPG work great on many other
problems.

Another great environment to try this on is `LunarLandingContinuous-v2`, but it will take
more episodes to obtain good results.
"""

# Save the weights
actor_model.save_weights("pendulum_actor.h5")
critic_model.save_weights("pendulum_critic.h5")

target_actor.save_weights("pendulum_target_actor.h5")
target_critic.save_weights("pendulum_target_critic.h5")

"""
Before Training:

![before_img](https://i.imgur.com/ox6b9rC.gif)
"""

"""
After 100 episodes:

![after_img](https://i.imgur.com/eEH8Cz6.gif)
"""



prev_state = initial_states
SS=[]
numstep = 0
u = []
u_n = []
c = 2
k = 5
b = 1.5
m = 5
w = 1
while True:
    # Uncomment this to see the Actor in action
    # But not in a python notebook.
    # env.render()
    t = numstep*0.1
    SS.append(prev_state)
    tf_prev_state = tf.expand_dims(tf.convert_to_tensor(prev_state-s_ref[numstep]), 0)

    action = policy1(tf_prev_state, ou_noise)
    #print(action)
    # Recieve state and reward from environment.
    #state, reward, done, info = env.step(action,numstep)
    y0 = ode.solve_ivp(sys, [t, t+0.1], prev_state, \
                           method = "RK45",t_eval=[t+0.1])
    state = y0.y[:,-1]
    s1 = state[0]
    s2 = state[1]
    #u.append(   (-1/(c*(4*1.2)))*(c*np.power(s2,2)+a*s2+c*4*s1))
    #u.append( m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) )
    u.append(  m* (-s2 + w*np.cos(w*t)-w*w*np.sin(w*t)+k/m*s1+c/m*s2) - np.sign(1+s1-np.sin(w*t)+s2-w*np.cos(w*t))*m )
    u_n.append(np.array(action))
    # End this episode when `done` is True
    if numstep>=149 :
        break

    prev_state = state
    numstep+=1

SMALL_SIZE = 32
MEDIUM_SIZE = 24
BIGGER_SIZE = 24
plt.rc('font', size=MEDIUM_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=SMALL_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=BIGGER_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=BIGGER_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=BIGGER_SIZE)    # legend fontsize
plt.rc('figure', titlesize=MEDIUM_SIZE)  # fontsize of the figure title



abcd = [':', '-.' ,'-','+-','--','x','*','3-', '|-']
abcd = [':', '-.' ,'+-','--','x','*','3-', '|-']
color1 = ['b' , 'g' , 'r' , 'tab:orange' , 'black' , 'mediumaquamarine' , 'deepskyblue' , 'tab:purple' , 'darkblue'  , 'darkred']
color1 = ['b' , 'g' , 'tab:orange' , 'black' , 'mediumaquamarine' , 'deepskyblue' , 'tab:purple' , 'darkblue'  , 'darkred']
fig, axs = plt.subplots(3,gridspec_kw={'height_ratios': [1, 1 , 1]})
x1 = np.arange(0,15,0.1)
SS = np.array(SS)
s_ref = np.array (s_ref)
s_ref2 = np.array(s_ref2)
fig.set_size_inches(20, 25)
###########################################################################
counter12 = 0
for i in range(2):
    s='$x_{%i}$' % (i+1)
    axs[0].plot(x1,SS[:,i],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
    counter12+=1
axs[0].plot(x1,u,abcd[counter12],c=color1[counter12],linewidth=2,label='$\hat{u}(\mathbf{x})$')
counter12+=1
axs[0].plot(x1,u_n,abcd[counter12],c=color1[counter12],linewidth=2,label='$u_{1}$')
counter12+=1
axs[0].plot(x1,y_ref,abcd[counter12],c='r',linewidth=2,label='$x_{1}^{ref}$')
axs[0].set(xlabel='time (s)')
axs[0].set_xlim(x1[0],x1[-1])
axs[0].set_ylim(-15,10)
axs[0].grid()
axs[0].legend(ncol=10,handleheight=1,loc='upper right')
axs[0].set_title('original system',fontsize='large',fontweight='bold')
#############################################################################
counter12 = 0
for i in range(2):
    s='$\hat{x}_{%i}$' % (i+1)
    axs[1].plot(x1,s_ref[:,i],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
    counter12+=1
axs[1].plot(x1,u_ref,abcd[counter12],c=color1[counter12],linewidth=2,label='$\hat{u}(\mathbf{\hat{x}})$')
axs[1].set(xlabel='time (s)')
axs[1].set_xlim(x1[0],x1[-1])
axs[1].set_ylim(-15,10)
axs[1].grid()
axs[1].legend(ncol=3,handleheight=1,loc='upper right')
axs[1].set_title('simplified system',fontsize='large',fontweight='bold')
#############################################################################
counter12 = 0
#for i in range(2):
    #s='$e_{%i}$' % (i+1)
    #axs[2].plot(x1,SS[:,i]-s_ref[:,i],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
    #counter12+=1
s='$e_{%i}$' % (1)
axs[2].plot(x1,SS[:,0]-s_ref[:,0],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
counter12+=1
s='$e_{%i}$' % (2)
axs[2].plot(x1,SS[:,1]-s_ref[:,1],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
counter12+=1
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s='$e_{%i}$ without DDPG' % (1)
axs[2].plot(x1,s_ref2[:,0]-s_ref[:,0],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
counter12+=1
s='$e_{%i}$ without DDPG' % (2)
axs[2].plot(x1,s_ref2[:,1]-s_ref[:,1],abcd[counter12],c=color1[counter12],linewidth=2,label=s)
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
axs[2].set(xlabel='time (s)')
axs[2].set_xlim(x1[0],x1[-1])
axs[2].set_ylim(-3,3)
axs[2].grid()
axs[2].legend(ncol=4,handleheight=2,loc='upper right')
axs[2].set_title('error system',fontsize='large',fontweight='bold')
#############################################################################
plt.subplots_adjust(hspace=0.3)
#fig.savefig(r'C:\Users\Sahand\Desktop\DHSA_tc_10ts_loss.jpg', dpi=200,bbox_inches = 'tight',pad_inches = 0)
plt.savefig('results.jpg',bbox_inches = 'tight')
from google.colab import files
files.download('results.jpg')

fig=plt.figure()
fig.set_size_inches(20, 10)
plt.plot(avg_reward_list,linewidth=2)
plt.xlabel("episode")
plt.ylabel("return ($G_{0}$)")
plt.grid()
plt.show()
fig.savefig('return.jpg',bbox_inches = 'tight')
files.download('return.jpg')



'''

prev_state = initial_states
SS=[]
numstep = 0
def sys2(t, y):
    s1, s2 , s3 = y
    a =1
    b =1
    c =1
    u = (-1/(c*(1.2)))*(c*np.power(s2,2)+a*2*s2+c*s1+b*2*s3)\
    -0.5*(1/(c*(1.2)))*np.sign(a*s1+b*s2+c*s3)
    dydt = [2*s2, 2*s3 , np.sin(s1) +np.power(s2,2)+ (1.2-np.exp(-np.absolute(s1)))*u ]
    return dydt


def sys2(t, y):
    s1, s2 = y
    c = 5
    k = 3
    b = -1.5
    u = -s2-c*s2 -1*np.sign(s1+s2) + action[0]
    dydt = [s2, -c*s2*np.abs(s2)-k*s1- b*np.power(s1,3)+u]
    return dydt


while True:
    numstep+=1
    # Uncomment this to see the Actor in action
    # But not in a python notebook.
    # env.render()
    SS.append(prev_state)
    tf_prev_state = tf.expand_dims(tf.convert_to_tensor(prev_state), 0)
    # Recieve state and reward from environment.
    #state, reward, done, info = env.step(action,numstep)
    y0 = ode.solve_ivp(sys2, [0, 0.1], prev_state, \
                           method = "RK45",t_eval=[0.1])
    state = y0.y[:,-1]
    # End this episode when `done` is True
    if numstep>=100 :
        break

    prev_state = state
    '''

'''
plt.cla()
plt.plot(range(len(SS)),SS)
plt.show()
'''







''''
def sys2(t, y):
    s1, s2 = y
    u = ( 1/(19.24+9.6*s2)  )*(2.8*s1-8.6*s2-5.8*np.power(s2,2)-2*np.power(s2,3)-2*s1*s2)\
        + ( 2/(19.24+9.6*s2)  )*np.sign(8.6*s1-5.8*s2-np.power(s2,2))
    dydt = [s1-s2 + u , s1+np.power(s2,2)+4.8*u]
    return dydt

s0 = np.array([0.5,0])
s_ref = []
for i in range(100):
    s_ref.append(s0)
    s0 = ode.solve_ivp(sys2, [0, 0.1], s0, \
                               method = "RK45",t_eval=[0.1])
    s0 = s0.y[:,-1]
plt.plot(range(len(s_ref)),s_ref)
'''

inputs = tf.keras.Input(shape = (2,))
# Unknown batch size

op = tf.gather(inputs, 1, axis=1)
print(op.shape)

